<?php 
$products = [
    0 => [
      'id' => '59838b71-2510-47e0-bd9b-319ca8b590d3',
      'name' => 'Gorgeous Wooden Fish',
      'size' => 'xxLarge',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Et eligendi quisquam culpa beatae dignissimos tenetur. Deserunt voluptates animi fugiat provident. Voluptates aut ut eligendi. Molestiae rerum maxime aut. Magni maiores dolorem dolores.',
    ],
    1 => [
      'id' => '2528c0b4-5895-4da8-82ff-5059fdfbcbe6',
      'name' => 'Refined Wooden Salad',
      'size' => 'large',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Animi est tempora dolor. Voluptatem dolorem quasi optio nostrum aut harum mollitia qui ea. Dolor delectus perspiciatis corrupti quae pariatur quos officiis ut. Tempora quod omnis asperiores aut omnis velit nihil. Molestias similique velit.',
    ],
    2 => [
      'id' => '24064f8d-204f-47f1-8011-429609fd1c7e',
      'name' => 'Practical Cotton Chair',
      'size' => 'small',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Distinctio ut occaecati saepe sint accusantium tempora qui. Provident quisquam praesentium vel beatae et. Nulla delectus corporis excepturi eligendi.',
    ],
    3 => [
      'id' => 'cbeb094b-3ccf-4844-b4e0-982e947f6062',
      'name' => 'Tasty Frozen Sausages',
      'size' => 'medium',
      'image' => 'http://placekitten.com/500/500',
      'paragraph' => 'Voluptatem odio omnis animi labore fuga. Enim possimus rerum sint sed voluptas quis nobis. Dignissimos tempore consequatur delectus ad occaecati et et in. Fuga nesciunt non eligendi dolor deserunt dolore deleniti. Numquam aperiam aut ut porro molestiae reiciendis. Qui perferendis laudantium ea rem similique.',
    ],
    4 => [
      'id' => '38e6b18f-aea3-47e0-a3b1-5d5c5b86d748',
      'name' => 'Unbranded Wooden Pants',
      'size' => 'large',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Est eos eum excepturi officiis totam. Alias dicta inventore mollitia dolorem omnis animi modi eos. Blanditiis voluptate et. Voluptatem fugiat libero asperiores quibusdam alias adipisci iusto. Consequatur non ea molestiae.',
    ],
    5 => [
      'id' => '7df0fb91-199e-4ccf-b97d-5f8564f24f91',
      'name' => 'Refined Cotton Shirt',
      'size' => 'xLarge',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Et eos magni dolor aliquam animi facilis. Molestias aut doloremque autem sed est sint dolor. Corporis rerum reprehenderit. Temporibus vero sapiente. Itaque explicabo occaecati mollitia. Est dignissimos modi vitae aliquid dignissimos.',
    ],
    6 => [
      'id' => '3cfecb7b-8ab5-4667-af32-28787fc639fa',
      'name' => 'Small Fresh Bacon',
      'size' => 'xLarge',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Ut maxime odit. Quia repellendus ducimus voluptas veniam dolores dolores fuga est totam. Nam voluptate qui. Vero quas dolores aut cupiditate repudiandae maiores. Et omnis et assumenda. Ratione excepturi ut aspernatur temporibus.',
    ],
    7 => [
      'id' => 'ae8ac74d-ae88-47a4-b80d-d21432b3d458',
      'name' => 'Refined Wooden Table',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Non dicta itaque tempore et assumenda quis facilis assumenda doloremque. Rerum dolorem molestias molestias tempore. Voluptate laudantium veniam est voluptas quaerat ex enim voluptas.',
    ],
    8 => [
      'id' => '18f2b484-cf59-4a49-9506-35fe787aaf0c',
      'name' => 'Handcrafted Granite Tuna',
      'size' => 'xxLarge',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Nihil incidunt iste ea. Ut et et assumenda qui itaque facilis dignissimos accusamus. Aliquam doloribus est. Fuga sapiente placeat sit numquam earum.',
    ],
    9 => [
      'id' => '0a2fd67d-1f90-40f8-8c7e-a89904ef98c3',
      'name' => 'Unbranded Metal Mouse',
      'size' => 'large',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Et accusantium aut. Praesentium consequatur asperiores molestiae. Repellendus quidem doloribus veritatis eos.',
    ],
    10 => [
      'id' => '699dd962-98ec-4c96-a319-a887400544c9',
      'name' => 'Handmade Cotton Cheese',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Qui quis enim cupiditate sit delectus excepturi mollitia. Rerum sit omnis quam laudantium voluptatibus. Impedit accusantium tempora deleniti aut sint rerum nostrum incidunt soluta.',
    ],
    11 => [
      'id' => '09d76c4a-7787-458c-b3e5-b83d28794ee8',
      'name' => 'Rustic Rubber Towels',
      'size' => 'small',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Natus veritatis quod totam nulla sint accusantium quia quaerat id. In exercitationem rerum aut delectus. Quis esse beatae quos rerum sit quas officiis consectetur. Placeat assumenda est magni excepturi tempore voluptatem aut asperiores.',
    ],
    12 => [
      'id' => 'd923687b-11f7-4904-910f-3e2cf1dae845',
      'name' => 'Small Concrete Pizza',
      'size' => 'xxLarge',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Ea harum non sit inventore quas ut saepe. Culpa maxime sed ab sapiente. Vitae molestias ut est vel qui nobis ut. Nostrum neque fuga recusandae ullam vel et. Et nihil ipsum nisi et necessitatibus eligendi eos. Magni voluptatem ipsam officia sit quia odio qui.',
    ],
    13 => [
      'id' => '529c2910-3729-44da-ba1e-889336e6ae15',
      'name' => 'Intelligent Frozen Soap',
      'size' => 'large',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Accusantium fuga iusto eius et repudiandae error ea voluptatem sunt. Autem recusandae odit facere molestiae velit odit unde totam. Sed cupiditate nihil a. Perferendis praesentium quos atque. Iure sed dolorem vitae nemo. Occaecati enim eius eum voluptatum sed est.',
    ],
    14 => [
      'id' => '5f7c3f10-3b87-47bc-a75d-73b75fa706c4',
      'name' => 'Tasty Fresh Soap',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Laboriosam iure dolore. Ducimus ab nemo suscipit eaque. Porro qui laudantium quidem et ea. Magnam qui quibusdam similique ducimus quod eum. Vero sit in in alias. Quo sint et reprehenderit est odit ea exercitationem nihil aut.',
    ],
    15 => [
      'id' => '5e047dc8-3c13-4c05-a042-2dc8237a3b02',
      'name' => 'Incredible Granite Pizza',
      'size' => 'large',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Voluptates ut voluptatibus aut totam. Amet magnam ab sed tempore et. Est in cumque reiciendis maxime occaecati porro deleniti cum. Et est perferendis nihil enim similique.',
    ],
    16 => [
      'id' => '0984fe41-a816-4b02-aa50-e4d9657a1304',
      'name' => 'Incredible Plastic Hat',
      'size' => 'xxSmall',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Exercitationem qui inventore. Fugiat molestiae est dolore odit est optio. Ipsa fugiat eum sint molestiae eum autem tempore. Architecto eum corrupti nihil consequatur quisquam.',
    ],
    17 => [
      'id' => 'ab6e127a-4a6d-4a08-83c0-4fb1f551e7d8',
      'name' => 'Unbranded Wooden Gloves',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Doloribus beatae sequi ut rerum. Iure numquam aut dolorem qui fugiat sed. Similique ab dolorem deleniti optio. Ipsam laudantium excepturi alias necessitatibus. Eos laborum sint facilis sit sunt sit veniam dicta quae.',
    ],
    18 => [
      'id' => '39274e73-ae11-4e91-b1f9-b8a81eadf737',
      'name' => 'Incredible Frozen Soap',
      'size' => 'xxSmall',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Et repellendus asperiores dolore qui. Quos saepe voluptatem nulla pariatur blanditiis voluptatem. Sed voluptatem aut ducimus modi fugit. Aut magnam commodi at fugit numquam accusantium qui eaque. Nihil cum asperiores sed quo corporis soluta. Impedit enim error vel ratione consequuntur fugit odio quibusdam.',
    ],
    19 => [
      'id' => '5568b771-921d-41d6-8f3b-99bec92ac4ca',
      'name' => 'Incredible Plastic Tuna',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Aliquid dolore autem quisquam aut unde sunt eum. Quos cupiditate quo amet. Eos sunt accusamus et beatae.',
    ],
    20 => [
      'id' => 'e6704204-9de6-4c99-ad9e-9661c78a1224',
      'name' => 'Tasty Plastic Hat',
      'size' => 'small',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Qui itaque ex aut debitis dolores quisquam omnis sed. Autem voluptas culpa et exercitationem et. Suscipit ea a quo illo possimus voluptatem ea possimus omnis. Sit et ea cupiditate.',
    ],
    21 => [
      'id' => '4d4718ad-abd5-44cb-b96f-8e5d091e4acc',
      'name' => 'Generic Fresh Pizza',
      'size' => 'xxLarge',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Totam eum velit debitis ducimus ipsa vitae labore. Dolores at aut unde mollitia ut quia. Et quasi et eos unde et voluptas ipsam nulla magni.',
    ],
    22 => [
      'id' => 'a3d9dbd8-094b-478f-bd31-73d7aae94a2a',
      'name' => 'Sleek Soft Salad',
      'size' => 'large',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Excepturi dolorum fuga dolor dicta nesciunt sit quidem dolorem. Cum dolorem ex quis consequatur expedita eum maxime. Excepturi et voluptates dolor esse et qui possimus quasi adipisci. Rerum a temporibus sequi quo dicta praesentium. Mollitia eaque doloremque natus nihil occaecati dolor cumque. Molestiae unde sit deleniti architecto eos quasi nulla.',
    ],
    23 => [
      'id' => 'dbe0a501-9a6c-459b-a728-bf7ca7560835',
      'name' => 'Handcrafted Concrete Mouse',
      'size' => 'xLarge',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Expedita fugiat illo id quia et quisquam quaerat. Asperiores voluptatem tenetur eligendi. Sunt molestiae rem perferendis.',
    ],
    24 => [
      'id' => 'fe7a6fb0-9d28-46e3-8356-aa9483faec23',
      'name' => 'Ergonomic Steel Pizza',
      'size' => 'large',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Cupiditate iste dolorem dicta. Quisquam ratione est et numquam dicta. Autem odit eos et laborum. Iusto distinctio debitis voluptatem culpa. Occaecati fugiat nobis dolores.',
    ],
    25 => [
      'id' => 'a89225a1-87ae-46f4-a927-5dfcc23ce907',
      'name' => 'Handcrafted Plastic Computer',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Fugiat porro quis libero amet ut totam. Voluptatum aliquid repudiandae. Quasi voluptates impedit ad sint. Placeat temporibus doloremque corporis dolor inventore atque facere. Debitis perferendis id corporis adipisci consequuntur blanditiis.',
    ],
    26 => [
      'id' => '78ac8faf-e04f-4cbb-849e-3ced83b75d58',
      'name' => 'Fantastic Concrete Ball',
      'size' => 'xLarge',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Enim optio temporibus aut molestiae soluta sed ullam et. Quia sed quasi ab facilis voluptatum vero. Voluptatem quidem voluptas neque aperiam omnis magnam suscipit. Eum dolorem qui id accusamus dolor harum officia.',
    ],
    27 => [
      'id' => '51866782-8434-4218-a352-abc7f451fe60',
      'name' => 'Refined Steel Pizza',
      'size' => 'small',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Corrupti quaerat maiores. Debitis rerum ut esse. Architecto quae pariatur laudantium est. Laborum quia eum. Sed ea vel. Inventore voluptate et totam.',
    ],
    28 => [
      'id' => 'f727e9db-a56b-4878-91d8-4acbc39c7fef',
      'name' => 'Incredible Rubber Bike',
      'size' => 'large',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Ipsum eum quam eos aut voluptas iusto consequuntur consequatur nihil. Maiores quis illum eum quidem cumque qui. Sequi ut recusandae et. Non quos dolores nesciunt. Nemo sit accusantium. Excepturi voluptas corrupti voluptas dolores rerum facere nulla.',
    ],
    29 => [
      'id' => 'ce8244c9-2385-4072-bf71-3808bf1132f1',
      'name' => 'Fantastic Frozen Shoes',
      'size' => 'small',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Omnis quas sint blanditiis amet. Et id explicabo eligendi perspiciatis et ipsa et tenetur. Hic veniam temporibus quo dolorem ea animi rerum. Voluptatem animi rerum commodi possimus atque.',
    ],
    30 => [
      'id' => 'd292b349-dfb4-462a-af84-85c9499a012f',
      'name' => 'Practical Plastic Chips',
      'size' => 'small',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Qui sunt aut molestiae nulla natus id autem. Voluptas rerum vitae sed. Velit enim cum eveniet labore dolor placeat ex aut id. Quidem corporis inventore qui molestiae quis rerum error ut nisi. Voluptatem ut eum maiores sed.',
    ],
    31 => [
      'id' => '01faab96-7fc4-44cb-977e-916c2d688f61',
      'name' => 'Unbranded Wooden Pizza',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Et beatae rerum voluptatem et aliquam quam in officia deleniti. Voluptate illum quia sunt pariatur et nihil eaque. Qui in eos.',
    ],
    32 => [
      'id' => '17c466e6-843b-46a6-a079-24aa57947da0',
      'name' => 'Unbranded Rubber Bacon',
      'size' => 'xxSmall',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Voluptatum quia perspiciatis quia perferendis ab sit. Vero laboriosam ipsam velit explicabo autem rerum qui. Iure et maiores omnis minus vero. Perferendis exercitationem quibusdam qui laborum aspernatur. Aspernatur quis nam ut ea suscipit rerum voluptas consequatur error. Est eaque aut vel quia dolorem.',
    ],
    33 => [
      'id' => '1ab0ba3f-4028-43dd-85a8-c9151a414792',
      'name' => 'Handmade Rubber Hat',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Accusantium quo modi. Repellendus incidunt tenetur est voluptatibus tempore facilis et repellat. Ducimus sed non vero beatae magni autem est recusandae.',
    ],
    34 => [
      'id' => 'e4b57970-181a-4d67-a2a1-8de98080a5c8',
      'name' => 'Practical Frozen Chips',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Esse nostrum necessitatibus impedit eius quae sit et iste ut. Et dignissimos est. Animi quia sequi enim aut aut aut qui autem. Veritatis qui quisquam et velit libero. Illo quos ipsam dignissimos consequatur voluptatem. Maxime magnam rerum et illo doloribus et molestias.',
    ],
    35 => [
      'id' => '6f2f2c91-b48d-40c0-b0d3-fdead0c9c42d',
      'name' => 'Awesome Plastic Bacon',
      'size' => 'large',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Recusandae quos sit quis et reprehenderit. Et quod eveniet nihil cumque aspernatur explicabo excepturi. Dolorem itaque quos.',
    ],
    36 => [
      'id' => '27438f5e-941c-416a-80ba-b37be9b29b4f',
      'name' => 'Awesome Fresh Pizza',
      'size' => 'xLarge',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Illum aut tempora eius distinctio adipisci ut aut. Quae pariatur ut autem sit consequatur eum quas est. Odio quia perspiciatis fugit harum quidem dolorem eaque cumque.',
    ],
    37 => [
      'id' => '694419c2-75d3-488b-8f3f-7bb2bf736ea6',
      'name' => 'Generic Wooden Towels',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Cupiditate sapiente sint totam tempora impedit illum at. Et laudantium et quis nam enim minus voluptatibus porro. At nostrum omnis qui. Non numquam nemo consequatur dicta possimus ut at soluta distinctio.',
    ],
    38 => [
      'id' => '24d786c2-a8b5-4c45-9a78-1cf61020942b',
      'name' => 'Tasty Concrete Chair',
      'size' => 'xLarge',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Nulla itaque velit. Maiores voluptas dolor non et numquam et enim. Quia occaecati assumenda esse. Aut temporibus et.',
    ],
    39 => [
      'id' => '3fca8b33-fa07-4de7-b9be-7a45f8bd1340',
      'name' => 'Tasty Cotton Pants',
      'size' => 'xxSmall',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Est soluta iste eos magni ratione quam doloribus et. Sequi rerum voluptatem iure dignissimos aut reprehenderit nobis ea ab. Magnam quasi velit optio possimus est minus natus accusamus quia. Nesciunt debitis non dolorem debitis voluptatum sint. Omnis qui sunt quas minus quia in neque. Iste qui est soluta consectetur.',
    ],
    40 => [
      'id' => '90983be8-e3ed-47ac-9213-fca36ae27f06',
      'name' => 'Fantastic Metal Mouse',
      'size' => 'xLarge',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Aut illum et iure. Voluptate in sunt illo consequatur amet. Cumque neque adipisci nihil aperiam repudiandae omnis. Occaecati vero illum asperiores iste nostrum at praesentium explicabo. Libero qui accusantium qui qui omnis ratione in voluptate enim.',
    ],
    41 => [
      'id' => 'd78213cf-94ad-46ab-9106-094296228daf',
      'name' => 'Gorgeous Soft Chips',
      'size' => 'large',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Aut quibusdam voluptatem dolor perferendis nemo veritatis at aut est. Earum aut consequuntur corporis temporibus beatae molestias cumque vitae. Itaque molestiae minus recusandae saepe quod qui vel aut culpa. Expedita aut at aut quam. Placeat molestias id ut.',
    ],
    42 => [
      'id' => 'e6fa1c4e-2718-4e00-8ddd-90483074ffa2',
      'name' => 'Refined Soft Fish',
      'size' => 'medium',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Autem error est adipisci eos aspernatur illo quae nesciunt consequatur. Et deserunt quia. Quo est rem nostrum distinctio et ad enim adipisci. Quasi quae unde doloremque magnam labore esse ut. Iure ducimus ut voluptate.',
    ],
    43 => [
      'id' => 'b3c777bd-6b44-47de-86af-f445bffb52ec',
      'name' => 'Awesome Wooden Cheese',
      'size' => 'xxSmall',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Aut facere dolorum recusandae modi. Libero quod nulla. Sed numquam vel dolorem qui omnis atque numquam ipsa. Voluptas qui omnis enim tempora. Vitae amet laborum culpa adipisci architecto.',
    ],
    44 => [
      'id' => '5f32ee32-0696-4a8f-9231-9bdf79e401a1',
      'name' => 'Awesome Soft Table',
      'size' => 'large',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Necessitatibus repellat qui et. Sed sint consectetur. Ea velit maxime velit nisi ut.',
    ],
    45 => [
      'id' => '6f272bbe-1f6b-40e5-b6f4-851df81efd38',
      'name' => 'Gorgeous Granite Shoes',
      'size' => 'large',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Nisi minus perspiciatis veritatis dignissimos nobis architecto. Ipsam aperiam dolore facilis doloremque tempore tenetur deleniti aut. Recusandae dolorem totam similique deserunt consequatur voluptatem. Unde eaque sint hic dicta nisi optio beatae.',
    ],
    46 => [
      'id' => 'e2b77c81-5231-4ca9-8914-2132ee586b6b',
      'name' => 'Handmade Soft Bike',
      'size' => 'xLarge',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Nihil aut ad. Nulla occaecati perferendis quia. Consequatur numquam maiores dolorem cum neque earum nam voluptates. Assumenda et soluta laborum quisquam neque dolor suscipit. Et tempore consectetur sunt molestias similique quae voluptas eius. Velit sapiente enim rerum cupiditate commodi error sapiente voluptatem.',
    ],
    47 => [
      'id' => '26740091-1b52-4ca3-bae6-ec9ca4eac6f6',
      'name' => 'Handmade Wooden Sausages',
      'size' => 'xxSmall',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Molestias voluptatem ipsam sint nam. Cupiditate neque architecto dolor voluptates est labore voluptatem repellendus. Dolorem fugiat aut ut sit odio minima. Omnis et at nulla qui id ratione similique. Harum explicabo est assumenda voluptatem aperiam alias incidunt debitis.',
    ],
    48 => [
      'id' => 'af3e6591-cb4c-4fc7-b391-ffbd2c110fd6',
      'name' => 'Refined Granite Mouse',
      'size' => 'large',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Deleniti sed corrupti rem quam nulla natus dolore delectus libero. Ut sed non consequatur nulla maiores. Suscipit quia voluptatibus autem recusandae optio minima. Voluptatem aut id ipsam.',
    ],
    49 => [
      'id' => 'f73723b7-08a2-4cfe-adf5-c3bab75d08ca',
      'name' => 'Practical Metal Tuna',
      'size' => 'xSmall',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Quibusdam molestiae hic perferendis rerum explicabo iure. Sequi omnis illum corporis. In necessitatibus autem optio. Fugiat exercitationem quos dolore reiciendis quisquam. Sunt fugit aut. Quaerat rerum nobis.',
    ],
    50 => [
      'id' => '641d7964-c19f-4b87-a8ba-f44c7f5868ef',
      'name' => 'Intelligent Frozen Soap',
      'size' => 'xxLarge',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Consequuntur et et. Id quae quos et voluptatem harum quam. Veritatis recusandae et dolor ab pariatur distinctio qui omnis. Adipisci possimus assumenda nam fugiat exercitationem est. Non eligendi consectetur qui deserunt. Sed adipisci temporibus repellat nulla fugiat consequuntur.',
    ],
    51 => [
      'id' => 'eebf403a-790b-4f45-a7cb-22c10d7935d9',
      'name' => 'Refined Wooden Sausages',
      'size' => 'medium',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Iure repellat quis sit quam eius dolorem molestias cum. Ea voluptas aperiam repudiandae sed eius. Sapiente inventore ad adipisci. Soluta aliquid et quas consequuntur voluptatem quasi aut quis pariatur. Enim accusantium dolore repellat temporibus itaque accusamus.',
    ],
    52 => [
      'id' => 'a6ebba9e-b9ca-4640-a5cd-aeb280cd5c79',
      'name' => 'Incredible Rubber Salad',
      'size' => 'large',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Ab fugit dignissimos reprehenderit at tempora laboriosam quia et. Sit voluptatem blanditiis provident voluptatibus quia eius ut expedita. Alias consequatur repudiandae illo in officiis iste ut magni. Est laborum ipsum. Qui tempora veniam assumenda. Atque cum molestiae.',
    ],
    53 => [
      'id' => '5cb7f035-2c70-46e5-80dd-fa9f53fb583b',
      'name' => 'Refined Rubber Car',
      'size' => 'small',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Ipsum accusantium consequatur optio quos. Sit fuga distinctio. Quasi hic esse. Expedita sint blanditiis delectus cupiditate. Inventore reiciendis dolorem ut adipisci. Praesentium voluptatem eligendi quibusdam consectetur ipsam suscipit quisquam.',
    ],
    54 => [
      'id' => '6f0ce9a9-59e2-4ee7-9fdd-a29d9d566087',
      'name' => 'Sleek Metal Bacon',
      'size' => 'xxLarge',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Quaerat tempore adipisci ducimus minima similique. Assumenda iusto et. Aut fuga repellendus neque atque excepturi. Veniam odio aliquid ab. Et repudiandae facere nihil minus molestiae voluptates fugit.',
    ],
    55 => [
      'id' => '07b0d07b-028d-47e9-9dae-4a1ac800caaf',
      'name' => 'Rustic Steel Cheese',
      'size' => 'xLarge',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Eius illum praesentium eius odio provident qui. Blanditiis facilis itaque quo error veritatis. Sequi accusamus expedita rerum. Sed soluta voluptas voluptatem ut dolor cupiditate qui nemo voluptatem. Eligendi enim aut ducimus aut ut aut.',
    ],
    56 => [
      'id' => 'f7ba5a0c-d43c-4991-b8a1-02a6c4549546',
      'name' => 'Generic Concrete Hat',
      'size' => 'large',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Non ipsa sit harum odio eum voluptates. Eius illo rerum illum. Non at earum voluptatem labore aliquam nemo sit. Asperiores in recusandae.',
    ],
    57 => [
      'id' => '0e7e1d65-59d2-491e-a431-1958ebadf4f3',
      'name' => 'Incredible Rubber Shirt',
      'size' => 'xxSmall',
      'image' => 'http://placekitten.com/500/600',
      'paragraph' => 'Assumenda ea pariatur sed est velit possimus. Rerum quam omnis corporis at illum. Enim ullam unde eos. Sit nihil consectetur et corporis aut exercitationem ex modi beatae.',
    ],
    58 => [
      'id' => '0799fe90-28ea-4e91-91f2-39e0166ca881',
      'name' => 'Rustic Granite Computer',
      'size' => 'xxLarge',
      'image' => 'http://placekitten.com/1200/1200',
      'paragraph' => 'Impedit cum quia eaque quis. Voluptatibus qui enim occaecati nam ipsum. Consequatur neque atque consequatur et ducimus occaecati pariatur.',
    ],
    59 => [
      'id' => 'a637d39a-23dd-47da-b8aa-337408b7ed3e',
      'name' => 'Awesome Steel Computer',
      'size' => 'medium',
      'image' => 'http://placekitten.com/600/600',
      'paragraph' => 'Fuga provident molestias a nihil omnis laborum asperiores magni. Rem et doloribus eos iste non voluptatum dolor. Veritatis provident omnis itaque. Quae eligendi molestias non voluptatem numquam repudiandae. Quisquam id in dolor. Voluptate porro molestias ut magni adipisci voluptatem voluptatum aut.',
    ],
  ];
